services:
  siprelay:
    container_name: siprelay
    image: siprelay:latest
    build: .
    restart: always
    #environment:
      #- API_PORT=8080
      #- SIP_UDP_PORT=5060
      #- SIP_TLS_PORT=5061
      #- SIP_TLS_KEY_PATH=/ssl/server.key
      #- SIP_TLS_CERT_PATH=/ssl/server.cert
    ports:
      - "5060:5060/udp"
      - "5061:5061/tcp"
      - "8080:8080/tcp"
    volumes:
      #- ./ssl:/ssl
      - /var/run/docker.sock:/var/run/docker.sock  # Allow watching Docker events
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - sip-net

networks:
  sip-net:
    driver: bridge